"""Make link optional

Revision ID: 69b78a0c595f
Revises: 8f488c04412c
Create Date: 2025-07-23 11:50:05.489546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b78a0c595f'
down_revision = '8f488c04412c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('job_link_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('job_link_key'), ['link'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###
