"""Initial migration

Revision ID: 8f488c04412c
Revises: 
Create Date: 2025-07-23 02:04:44.918160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f488c04412c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=300), nullable=True))
        batch_op.create_unique_constraint(None, ['link'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('link')

    # ### end Alembic commands ###
