"""Make link nullable

Revision ID: ff4f487725d1
Revises: 69b78a0c595f
Create Date: 2025-07-23 12:03:49.894829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4f487725d1'
down_revision = '69b78a0c595f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###
